In [1]:
import numpy as np


In [2]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [3]:
a = np.arange(1,10,2).reshape(5,1).shape

In [4]:
np.arange(50,1,-1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [5]:
np.eye(10).shape

(10, 10)

In [6]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.random.rand(10).reshape(2,5)

array([[0.1303136 , 0.0258175 , 0.3324129 , 0.57471698, 0.68613475],
       [0.25652367, 0.87797206, 0.45969069, 0.37475293, 0.76803869]])

In [8]:
np.random.randn(4,4)

array([[-0.60574052, -0.00872443,  0.06634263, -1.26415357],
       [-1.27959252, -0.04784977,  0.81545208,  0.18384807],
       [-0.18904294,  0.75952263,  0.07444692, -0.84266448],
       [ 1.50892253, -0.44293625, -0.9211375 ,  0.15408747]])

In [9]:
np.random.randint(1,100,20).reshape(4,5)

array([[13, 66, 62, 55, 39],
       [ 2, 62, 42, 36,  6],
       [ 5, 69, 87, 25, 34],
       [56, 60, 98,  9, 76]])

In [10]:
np.random.randint(1,100,(4,4))

array([[24, 30, 80, 56],
       [95, 64, 64, 93],
       [25, 29, 89, 87],
       [ 3, 27, 96, 71]])

In [11]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr = arr.reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
print(arr[1:7:1])

[[ 6  7  8  9 10]]


In [14]:
print(arr[-1:3:-1])

[]


In [15]:
print(arr[0:1,-1:3:-1])

[[5]]


In [16]:
arr1 = np.random.randint(2,100,20).reshape(5,4)

In [17]:
print(arr1)

[[80 54 34 42]
 [45 41 62 80]
 [ 9 15 48 59]
 [ 7 30  2 31]
 [57 95  5 53]]


In [18]:
print(arr1[:3,:])

[[80 54 34 42]
 [45 41 62 80]
 [ 9 15 48 59]]


In [19]:
print(arr1[0:3,0:3])

[[80 54 34]
 [45 41 62]
 [ 9 15 48]]


In [20]:
print(arr1[:,:])

[[80 54 34 42]
 [45 41 62 80]
 [ 9 15 48 59]
 [ 7 30  2 31]
 [57 95  5 53]]


In [21]:
print(arr1[2:4,1:3])

[[15 48]
 [30  2]]


In [22]:
print(arr1[-3:-1,-3:-1])

[[15 48]
 [30  2]]


In [23]:
print(arr1)
print(arr1[2:4,::3])

[[80 54 34 42]
 [45 41 62 80]
 [ 9 15 48 59]
 [ 7 30  2 31]
 [57 95  5 53]]
[[ 9 59]
 [ 7 31]]


In [24]:
x = np.zeros((2,3,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [25]:
x.ndim

3

In [26]:
x = np.ones((2,3),np.int8)
print(x)
print(x.ndim)
print(x.strides)

[[1 1 1]
 [1 1 1]]
2
(3, 1)


In [27]:
x.data

In [28]:
x.size

6

In [29]:
x.itemsize

1

In [30]:
x.nbytes

6