In [51]:
import pandas as pd
import numpy as np

In [52]:
data1 = np.arange(0,20).reshape(5,4)

In [53]:
df = pd.DataFrame(data1)
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [54]:
df = pd.DataFrame(data=data1,index=["R1","R2","R3","R4","R5"],columns=["C1","C2","C3","C4"])
df

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [55]:
type(df)

pandas.core.frame.DataFrame

In [56]:
df.head()

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [57]:
df.head(2)

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7

In [58]:
df.tail()

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [59]:
df.tail(3)

C1  C2  C3  C4
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [60]:
df.describe()

C1         C2         C3         C4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [61]:
df.describe().mean()

C1    7.415569
C2    8.165569
C3    8.915569
C4    9.665569
dtype: float64

In [62]:
df[['C1','C2']]

C1  C2
R1   0   1
R2   4   5
R3   8   9
R4  12  13
R5  16  17

In [63]:
print(type(df[["C1"]]))
print(type(df['C1']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [64]:
df['C1']

R1     0
R2     4
R3     8
R4    12
R5    16
Name: C1, dtype: int32

In [65]:
df.loc[['R1','R2']]

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7

In [66]:
df.loc[['R1','R2'],['C1','C2']]

C1  C2
R1   0   1
R2   4   5

In [67]:
df.iloc[0:4,:]

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15

In [68]:
df.iloc[0:3,0:2]

C1  C2
R1   0   1
R2   4   5
R3   8   9

In [69]:
df

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [70]:
df.iloc[2:4,1:3]

C2  C3
R3   9  10
R4  13  14

In [71]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [72]:
np.nan

nan

In [73]:
type(np.nan)

float

In [74]:
data2 = np.array([[1,np.nan,3],[4,5,6]])
data2

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.]])

In [75]:
df1 = pd.DataFrame(data=data2,index=['R1','R2'],columns=['C1','C2','C3'])
df1

C1   C2   C3
R1  1.0  NaN  3.0
R2  4.0  5.0  6.0

In [76]:
df1.isnull()

C1     C2     C3
R1  False   True  False
R2  False  False  False

In [77]:
df1.isnull().sum()

C1    0
C2    1
C3    0
dtype: int64

In [78]:
df1.isna()

C1     C2     C3
R1  False   True  False
R2  False  False  False

In [79]:
df

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [80]:
df.iloc[:,1:2]

C2
R1   1
R2   5
R3   9
R4  13
R5  17

In [81]:
df.iloc[:,1:2]

C2
R1   1
R2   5
R3   9
R4  13
R5  17

In [83]:
print(type(df.iloc[:,:]))

<class 'pandas.core.frame.DataFrame'>


In [85]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, R1 to R2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   C1      2 non-null      float64
 1   C2      1 non-null      float64
 2   C3      2 non-null      float64
dtypes: float64(3)
memory usage: 64.0+ bytes


In [86]:
df1.head()

C1   C2   C3
R1  1.0  NaN  3.0
R2  4.0  5.0  6.0

In [89]:
df1[['C1','C2']].value_counts()

C1   C2 
4.0  5.0    1
Name: count, dtype: int64

In [90]:
df1.iloc[:,:].nunique()

C1    2
C2    1
C3    2
dtype: int64

In [91]:
df1['C1'].unique()

array([1., 4.])

In [92]:
df1['C1'].nunique()

2

In [94]:
df1.nunique()

C1    2
C2    1
C3    2
dtype: int64

In [95]:
df.nunique(axis=0)

C1    5
C2    5
C3    5
C4    5
dtype: int64

In [96]:
df.nunique(axis=1)

R1    4
R2    4
R3    4
R4    4
R5    4
dtype: int64

In [103]:
df.to_csv("t1.csv",sep=',',index=False)

In [104]:
df2 = pd.read_csv('t1.csv')
df2

C1  C2  C3  C4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [101]:
df[df['C1']>5]

C1  C2  C3  C4
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [102]:
df[df.isnull()]

C1  C2  C3  C4
R1 NaN NaN NaN NaN
R2 NaN NaN NaN NaN
R3 NaN NaN NaN NaN
R4 NaN NaN NaN NaN
R5 NaN NaN NaN NaN

In [107]:
df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [108]:
df2

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]